    FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0 # X-Pack plugins enabled

	# RUN bin/elasticsearch-plugin install ingest-geoip


