FROM nginx

# install essential Linux packages
RUN apt-get update -qq && apt-get -y install apache2-utils

# move nginx config into correct location
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]
